name: Check Linting

on: push

jobs:
  markdown-lint:
    name: Lint markdown files (check links validity)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check the validity of the links in the documentation
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          folder-path: "."
